<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYs3e9xA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYs3e9xA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYs3e9xA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYs3e9xA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYs3e9xA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ys3e9xA',
    'container.build_id' => 'a9d809c2',
    'container.build_time' => 1674337870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYs3e9xA');
